CallFail04.z2(12, 9): error:
	Class 'CallFail04' does not have an overload
		test(org.z2legacy.ut.call.Foo)
	existing overloads
		test(ref org.z2legacy.ut.call.Foo)

